// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CheckAllHobby(ctx context.Context, userID int64) ([]Hobby, error)
	CheckHobbyWithPage(ctx context.Context, arg CheckHobbyWithPageParams) ([]Hobby, error)
	CreateHobby(ctx context.Context, arg CreateHobbyParams) (Hobby, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHobby(ctx context.Context, id int64) error
	GetHobby(ctx context.Context, userID int64) (Hobby, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateHobby(ctx context.Context, arg UpdateHobbyParams) (Hobby, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
