// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CheckHobbyWithPage(ctx context.Context, arg CheckHobbyWithPageParams) ([]Hobby, error)
	CreateHobby(ctx context.Context, arg CreateHobbyParams) (Hobby, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHobby(ctx context.Context, id int64) error
	GetAllUser(ctx context.Context) ([]User, error)
	GetHobby(ctx context.Context) ([]Hobby, error)
	GetHobbyByUserId(ctx context.Context, userID int64) ([]Hobby, error)
	GetHobbyForUpdate(ctx context.Context, id int64) (Hobby, error)
	GetHobbywithUser(ctx context.Context) ([]GetHobbywithUserRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
	UpdateHobby(ctx context.Context, arg UpdateHobbyParams) (Hobby, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
